server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-ribbon-consumer
    api-b:
      path: /api-b/**
      serviceId: eureka-feign-consumer
      
spring:
  application:
    name: microservice-zuul